name: WakaTime Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "10 7 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: wakatime-gist
        uses: tadeasf/wakatime-box@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKA_API_KEY: ${{ secrets.WAKA_API_KEY }}
          GIST_ID: ${{ secrets.GIST_ID }}
          WAKATIME_BASE_URL: ${{ secrets.WAKATIME_BASE_URL }}
          DATE_RANGE: 'last_7_days'
          MAX_LANGUAGES: 5
          MAX_PROJECTS: 5
          PRINT_SUMMARY: true
          USE_OLD_FORMAT: false